name: Build and Deploy to ECS

on:
    push:
        branches:
            - main # 或你要触发部署的分支

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build Rspress project
              run: pnpm build

            - name: Deploy to ECS via SCP
              uses: appleboy/scp-action@v0.1.3
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  source: 'LazyBlog'
                  target: '/var/www'
